### ISSUE TITLE
Change the Cargo.toml `package.repository` keys to point to the actual folders

### ISSUE THREAD

**Issue by rrbutani** [ut-utp/core#103]
### what

What the title says. [Here](https://github.com/rustwasm/wasm-bindgen/blob/1e1cab6202519dec2c30314e26aa3c8f601f3506/crates/web-sys/Cargo.toml#L8)'s an example.

```TOML
# For lc3-baseline-sim:
# this:
repository = "http://github.com/ut-utp/prototype/tree/master/baseline-sim"
# instead of this:
repository = "http://github.com/ut-utp/prototype"
```
This should happen with or after the rename (#31).

### steps
 - [ ] [app-support](https://github.com/ut-utp/core/tree/master/application-support/Cargo.toml#L11)
 - [ ] [baseline-sim](https://github.com/ut-utp/core/tree/master/baseline-sim/Cargo.toml#L11)
 - [ ] [device-support](https://github.com/ut-utp/core/tree/master/device-support/Cargo.toml#L11)
 - [ ] [isa](https://github.com/ut-utp/core/tree/master/isa/Cargo.toml#L11)
 - [ ] [macros](https://github.com/ut-utp/core/tree/master/macros/Cargo.toml#L11)
 - [ ] [os](https://github.com/ut-utp/core/tree/master/os/Cargo.toml#L11)
 - [ ] [shims](https://github.com/ut-utp/core/tree/master/shims/Cargo.toml#L11)
 - [ ] [test-infrastructure](https://github.com/ut-utp/core/tree/master/test-infrastructure/Cargo.toml#L12)
 - [ ] [traits](https://github.com/ut-utp/core/tree/master/traits/Cargo.toml#L11)
 - [ ] the other multi-crate (workspace) repos:
   + [ ] [assembler](https://github.com/ut-utp/assembler)
   + [ ] [tui](https://github.com/ut-utp/tui)
   + [ ] [tools](https://github.com/ut-utp/tools)

### where
branch: N/A

### open questions

None!
